services:
  - type: web
    name: angular-talents-backend
    runtime: docker
    plan: free
    region: frankfurt
    envVars:
      - key: MONGO_DB_ACCOUNT
        sync: false
      - key: MONGO_DB_PASS
        sync: false
